#!/usr/bin/env bash
# SFT distillation baseline launcher.
#
# Trains Qwen3-1.7B on Qwen3-8B teacher responses (parquet pre-generated by
# baselines/sft_distill/generate_teacher_responses.py). Hyperparams come
# from baselines/sft_distill/sft_distill_v1.0_base.yaml; override on the
# CLI as needed.
#
# Usage (run from repo root):
#   bash baselines/sft_distill/run_sft_distill.sh                  # 4 GPUs
#   NPROC=2 bash baselines/sft_distill/run_sft_distill.sh          # 2 GPUs
#   bash baselines/sft_distill/run_sft_distill.sh trainer.total_epochs=1

set -xeuo pipefail

CONFIG_NAME=${CONFIG_NAME:-sft_distill_v1.0_base}
NPROC=${NPROC:-4}
CONFIG_DIR=${CONFIG_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
# verl is installed only in the repo-local venv, not in the system python.
TORCHRUN=${TORCHRUN:-.venv/bin/torchrun}

"${TORCHRUN}" --standalone --nnodes=1 --nproc-per-node="${NPROC}" \
    -m verl.trainer.fsdp_sft_trainer \
    --config-path="${CONFIG_DIR}" \
    --config-name="${CONFIG_NAME}" \
    "$@"
